/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fops;
import db.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import util.*;


/**
 *
 * @author brennan
 */
public class mainUI extends javax.swing.JFrame {
    private FopsDB db;
    /** 
     * Creates new form mainUI
     */
    
    public mainUI() {
        super("Faculty Organization Planning Software [FOPS]");
        db = new FopsDB();
        initComponents();
        commViewButton.setActionCommand("committee");
        facultyViewButton.setActionCommand("faculty");
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewGroup = new javax.swing.ButtonGroup();
        filterTextField = new javax.swing.JTextField();
        commViewButton = new javax.swing.JRadioButton();
        facultyViewButton = new javax.swing.JRadioButton();
        filterButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainList = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        saveMenu = new javax.swing.JMenuItem();
        addFaculty = new javax.swing.JMenuItem();
        addCommittee = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        filterTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTextFieldActionPerformed(evt);
            }
        });

        viewGroup.add(commViewButton);
        commViewButton.setSelected(true);
        commViewButton.setText("Committee View");
        commViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commViewButtonActionPerformed(evt);
            }
        });

        viewGroup.add(facultyViewButton);
        facultyViewButton.setText("Faculty View");
        facultyViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyViewButtonActionPerformed(evt);
            }
        });

        filterButton.setText("Filter");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        mainList.setModel(new DefaultListModel());
        mainList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(mainList);

        menu.setText("File");

        saveMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenu.setText("Save");
        saveMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuActionPerformed(evt);
            }
        });
        menu.add(saveMenu);

        addFaculty.setText("Add Faculty");
        addFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyActionPerformed(evt);
            }
        });
        menu.add(addFaculty);

        addCommittee.setText("Add Committee");
        addCommittee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommitteeActionPerformed(evt);
            }
        });
        menu.add(addCommittee);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(commViewButton)
                                .addGap(18, 18, 18)
                                .addComponent(facultyViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 449, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commViewButton)
                    .addComponent(facultyViewButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void createListModel(){
        String filter = filterTextField.getText();
        if(filter.equals("")){
            filter = "*";
        }
        Glob glob = new Glob(filter);
        if(viewGroup.getSelection().getActionCommand() == null){
            committeeListModel(glob);
        }
        if(viewGroup.getSelection().getActionCommand().equals("committee")){
           committeeListModel(glob);
        }
        facultyListModel(glob);
        
            
    }
    
    private void committeeListModel(Glob glob) {
        List<String> names= new ArrayList<>();
        Collection<Committee> comms = db.getAllCommittees();
        System.out.println(comms.size());
        for(Committee comm : comms){
            
            if(glob.matches(comm.getName())){
                System.out.println(comm.getName());
                System.out.println("heyo got here");
                names.add(comm.getName());
                
            }
        }
        System.out.println(names.size());
        generateListModel(names);
        
    }
    
    private void facultyListModel(Glob glob){
        List<String> faculty = new ArrayList<>();
        for(Staff fac : db.getAllFaculty()){
            if(glob.matches(fac.getName())){
                faculty.add(fac.toString());
            }
        }
        generateListModel(faculty);
        
    }
    
    private void generateListModel(List<String> s){
        DefaultListModel model = new DefaultListModel();
       // DefaultListModel model = (DefaultListModel) mainList.getModel();
        model.removeAllElements();
        System.out.println(s.size());
        for(String str : s){
            model.addElement(str);
        }
        mainList.setModel(model);
        System.out.println(model.firstElement());
        mainList.setSelectedIndex(0);
        
        
        
    }
    
    private void saveMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuActionPerformed
        
    }//GEN-LAST:event_saveMenuActionPerformed

    private void addFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyActionPerformed
        new addFacultyUI("Add Faculty", db);
    }//GEN-LAST:event_addFacultyActionPerformed

    private void addCommitteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommitteeActionPerformed
        new AddCommUI("Add Committee", db);
    }//GEN-LAST:event_addCommitteeActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        createListModel();
    }//GEN-LAST:event_filterButtonActionPerformed

    private void commViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commViewButtonActionPerformed
        createListModel();
        //facultyViewButtonActionPerformed(evt);
    }//GEN-LAST:event_commViewButtonActionPerformed

    private void facultyViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyViewButtonActionPerformed
        createListModel();
    }//GEN-LAST:event_facultyViewButtonActionPerformed

    private void filterTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filterTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addCommittee;
    private javax.swing.JMenuItem addFaculty;
    private javax.swing.JRadioButton commViewButton;
    private javax.swing.JRadioButton facultyViewButton;
    private javax.swing.JButton filterButton;
    private javax.swing.JTextField filterTextField;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList mainList;
    private javax.swing.JMenu menu;
    private javax.swing.JMenuItem saveMenu;
    private javax.swing.ButtonGroup viewGroup;
    // End of variables declaration//GEN-END:variables
}
