package db.values;

/**
 * Disciplines at UMW.
 */
public  enum Discipline {
    AMER_STUDIES, ANTHROPOLOGY, ARTS, BIOLOGY, CHEMISTRY,
    CLASSICS, COMP_SCI, ECONOMICS, ENGLISH, ENV_SCI,
    FRENCH, GEOGRAPHY, GEOLOGY, HIST_PRESERVATION, HISTORY,
    INATL_AFFAIRS, LATIN, MATH, FOREIGN_LANG, MUSIC, PHILOSOPHY,
    PHYSICS, POLY_SCI, PSYCH, RELIGION, SOCIOLOGY, THEATRE,
    GENDER_STUDIES
}
